### PR TITLE
Routine updates

### PR DESCRIPTION
**Pull request by elliotweiser**
Emergency updates
-----------------

* Update `pip` requirements, and prune unused packages (e.g. PyCrypto)

This addresses the issue concerning dependencies with known security
vulnerabilities.

Additional updates
------------------

* Support newer distro versions for Alpine, Fedora, Ubuntu, and Debian
* Address deprecation warning for 'include' directive (now requires Ansible 2.4+)
* Fix idempotence issue for required Alpine package

Changes to facilitate/simplify testing
--------------------------------------

* Set `SDKMAN_DIR` environment variable at play level
* Install consistent Java version using SDKMAN
* Remove redundant testing re: installing Maven
* Stop testing against EOL linux distros
* Validate SSL when downloading SDKMAN script
* Remove syslog from container creation (removed downstream)

### CODE REVIEW

**Comment by elliotweiser** [comment]
@rwaweber Please give this a look-over when you get a chance. I think this will supersede #16. Since it addresses the identified dependency issues, I'd like to merge this ASAP.

**Comment by rwaweber** [comment]
Sounds good to me! I think the only things that might fail here could be the truthiness things that would be caught in a `molecule lint`, but other than that all the dependencies look good to me. I don't have write access so I can't manually test my hypothesis with Travis unfortunately.

**Comment by elliotweiser** [comment]
I actually disabled the truthy check because a) it's failing on warnings, but only from molecule, and b) loose truthy rules are normal for Ansible (e.g. `becomes: yes`).

**Comment by elliotweiser** [comment]
I'll open a separate issue on Molecule to address the yamllint issues.

**Comment by rwaweber** [comment]
Cool, looks good to me! 👍

**Comment by kristakhare** [comment]
Thank you so much @elliotweiser and @rwaweber

**Pull request merged**
